AWSTemplateFormatVersion: '2010-09-09'
Description: S3 bucket with secure settings
Resources:
  GoodBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub good-bucket-${AWS::AccountId}-${AWS::Region}
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
