AWSTemplateFormatVersion: '2010-09-09'
Description: Secure S3 bucket with best practices
Resources:
  GoodBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub good-bucket-${AWS::AccountId}-${AWS::Region}
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      LoggingConfiguration:
        DestinationBucketName: !Sub good-bucket-logs-${AWS::AccountId}-${AWS::Region}
        LogFilePrefix: access-logs/
      LifecycleConfiguration:
        Rules:
          - Id: TransitionToGlacier
            Status: Enabled
            Prefix: ""
            Transitions:
              - StorageClass: GLACIER
                TransitionInDays: 30
      Tags:
        - Key: Environment
          Value: Production
        - Key: Role
          Value: BackupStorage
        - Key: Name
          Value: GoodBucket

  GoodBucketLogs:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub good-bucket-logs-${AWS::AccountId}-${AWS::Region}
      AccessControl: LogDeliveryWrite
